version: '3'

services:
  api:
    build: ./
    restart: unless-stopped
    command: "npm run dev"
    volumes:
      - ./src/:/app/src/
      - ./.env:/app/.env
    ports:
      - $PORTA:$PORTA
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$MONGO_USER"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGO_PASS"
    # volumes:
    #   - ./mongo-data:/data/db